//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBrms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodCart
    {
        public int FoodCartId { get; set; }
        public int FoodId { get; set; }
        public int CartId { get; set; }
        public int Quantity { get; set; }
        public double Price { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Food Food { get; set; }
    }
}
