//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBrms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodOrder
    {
        public int FoodOrderId { get; set; }
        public int FoodId { get; set; }
        public int OrderId { get; set; }
        public int Qunatity { get; set; }
        public System.DateTime Date { get; set; }
        public double Price { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
