//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBrms.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Magazine
    {
        public int MagazineId { get; set; }
        [DisplayName("Magazine Title")]
        public string Name { get; set; }
        public string Image { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
